### PR TITLE
Added support for HTML5 link attributes

### PR DESCRIPTION
**Pull request by rarous**

### CODE REVIEW

**Comment by cwelch5** [comment]
Thanks for the PR. I'd like to understand your use case because we'd like to try a global solve for this if possible. Are you trying to prevent adding multiple link tags with the same `media` attribute for example?

**Comment by cwelch5** [comment]
@rarous If we open up these tag attributes now, order of attributes in link tags will seriously matter and this may break a lot of people's code out there.  I have an idea for a global solution where users can easily indicate which attributes they want to make "primary" within the tag.  Once that is in place, we can add in these types of tag attributes to cover the full link spec.

**Comment by ihsansatriawan** [comment]
hi @cwelch5 , how use your global solution for added tag not provided react-helmet ? such `hreflang`

**Comment by ihsansatriawan** [comment]
@cwelch5 but in documentation, never mention about `hreflang`, i have tried for put `<link rel="alternate" hreflang="x-default" href="https://myweb.com" />`

with react helmet 
```
link={[
            { rel: 'shortcut icon', href: require('../img/favicon.ico') },
            { rel: 'alternate', hreflang:'x-default', href: 'https://myweb.com' }
          ]}
```

but in html just `<link data-react-helmet="true" rel="alternate" href="https://myweb.com"/>`

**Comment by elyobo** [comment]
Has a proper way for doing this been added?  Lack of `hreflang` is problematic if you have multilingual content and would like Google to realise that.

**Comment by elyobo** [comment]
Cancel that, it seems to work fine if you use the casing that react wants, i.e. `hrefLang` not `hreflang`.

**Comment by brendanmh** [comment]
Has this been resolved? It would be nice to have a way to make hrefLang be the primary attribute, so we could override duplicates.

**Pull request closed without merging**
