### PR TITLE
optimize getInnermostProperty

### PR DESCRIPTION
**Pull request by Artazor**
It is very strange to create a new list every time when we need simply a reverse iteration -)

### CODE REVIEW

**Comment by Artazor** [comment]
@cwelch5 um?

**Comment by doctyper** [comment]
@Artazor The goal here was to keep this property list immutable. That is, we return a copy of the list, not the list itself. It helps prevent against possible side-effects.

**Comment by Artazor** [comment]
@doctyper do you mean that evaluating
```js
if (props[property]) {
   return props[property];
}
```
may somehow change the `propsList` (e.g. via getters) ?

**Comment by doctyper** [comment]
I meant that copying the property list ensures the intent of this method. On closer look however, your method does the same and is more efficient. 👍

**Pull request merged**
