### PR TITLE
Bundle helmet using rollup

### PR DESCRIPTION
**Pull request by realityking**
This PR adds rollup to bundle helmet into a single module for CJS and ESM.

The main advantage is smaller code size (about 8% for the CommonJS version) due to inlined exports and deduplicated babel helpers. It will also improve start up time a little bit when bundling the CommonJS version with Webpack, as it creates a function invocation for every module.

Lastly, this help minifies and optimisers more easily see the code paths taken and allow them to drop/inline more things when bundling.

Note that this will be braking change:

- The file structure changed and you can't deep require the utils and constants anymore
- I removed the default export from Helmet.js as it doesn't work well with rollup. It also seems unnecessary since all documentation is using the named export.

### CODE REVIEW

**Comment by realityking** [comment]
The test failure is unrelated to this change. Fix in #397.

**Comment by tmbtech** [comment]
@realityking Thank you for this PR, this one makes sense to me. I'll review and get back to you early next week. Sorry for the delay, I'm going to jumping in for Chris.

**Comment by tmbtech** [comment]
@realityking quick update. I talked with @cwelch5 over the weekend and we are both like the idea of moving to rollup. The plan is to test internally, bumping a major version, then npm publishing a beta version for feedback. It's going to take a little bit to get all this formalized, but we are making good progress.

**Comment by tmbtech** [comment]
@realityking doesn't look like travis / node v4 likes the latest branch. Let me find out if node 4, is still a requirement, or if we can take it out of the build step.

**Comment by tmbtech** [comment]
According to this link, https://github.com/nodejs/Release, 4 is EOL. We should remove it from the travis build checks.

**Comment by tmbtech** [comment]
https://github.com/nfl/react-helmet/issues/414

**Pull request merged**
