### PR TITLE
Adding peerDependency for react

### PR DESCRIPTION
**Pull request by PepijnSenders**
When installing the package it should prompt to install `react`, without `react` the package doesn't work.

### CODE REVIEW

**Comment by cwelch5** [comment]
We used to have peer dependencies included in the package.json but it became unruly to maintain.  We also didn't want to pin users to only a specific set of React versions.  We do however need a way to indicate to users what React versions are compatible.

**Comment by PepijnSenders** [comment]
You can also just use `*` as a dependency version 😉.

**Comment by PepijnSenders** [comment]
Anyways, I think the open source community will tell you when you need to update your `react` version.

**Comment by cwelch5** [comment]
@PepijnSenders yes, they will tell us, but also the community will be smart enough to update their React version as well.  We appreciate the PR but we'll keep peerDependencies out for now.  Thanks.

**Pull request closed without merging**
