### PR TITLE
React-helmet: Removed phantomjs dependency

### PR DESCRIPTION
**Pull request by ossdev07**
PhantomJS is unmaintained removed dependency from package.json and karma.conf.js.
Updated node_js version to 7 and 8 in travis.yml beacuse earlier version 4 and 5 were very old.

Signed-off-by: ossdev07 <ossdev@puresoftware.com>

### CODE REVIEW

**Comment by ossdev07** [comment]
Ping @jamsea @cwelch5 

Can you please have a look at this PR.
It will be a delight to see phantomjs dependency removed from react-helmet.

**Comment by jamsea** [comment]
Looks good to me @ossdev07! I'm not at the NFL any more though so I can't merge it 👎

**Comment by ossdev07** [comment]
@jamsea 

Thanks for your time.
Could you please suggest who here will be able to merge this PR.

**Comment by jamsea** [comment]
@miblanchard @tmbtech should be able to help. Guessing Chris doesn't have Github tied to his email

**Comment by cwelch5** [comment]
thanks @jamsea how you been?

**Comment by ossdev07** [comment]
Thanks for approving this PR @cwelch5 @jamsea

**Pull request merged**
