### PR TITLE
Fix compatibility with React 16.8

### PR DESCRIPTION
**Pull request by Volune**
Fix for #441 replace deepEqual with isEqual. And prepare changelog for 5.2.1 release.

### CODE REVIEW

**Comment by tshen8** [comment]
Looks like this change may involve dropping support for Node 4 and 5?

**Comment by Volune** [comment]
> Looks like this change may involve dropping support for Node 4 and 5?

Doesn't seem related to the code change, it failed inside npm: https://travis-ci.org/nfl/react-helmet/jobs/502989803

(Also Node themselves [already dropped support for node 4 and 5](https://nodejs.org/en/about/releases/))

**Comment by janhartmann** [comment]
Can we have an update to this, please?

**Comment by Dakkers** [comment]
Can you please take a look at this? @cwelch5

**Comment by Dakkers** [comment]
@Volune I've published your changes to https://www.npmjs.com/package/@bidvine/react-helmet

(this is a temporary package and we won't maintain it beyond these changes, it's currently blocking something of ours)

**Comment by IanVS** [comment]
Since this was merged into the release branch for `5.2.0`, I think `master` does not have it, right?  Also, it won't be in `6.0.0-beta`.  I'm trying to figure out what version to add to my project, as I'm just now starting to use it.  I'm a bit confused.  😕

**Comment by tmbtech** [comment]
@IanVS 5.2.0 and 6.0.0-beta both have a fix. The difference is 6.0 is not backward compatible since there was an upgrade to rollup. 

6.0.0 Updated the import statement. 
https://github.com/nfl/react-helmet/pull/421#issuecomment-450449810

**Comment by gabrielizaias** [comment]
I saw that there's not tag for `5.2.1` on the repository, but npm shows it as the latest stable version. For a moment I was worried that this package might have been compromised.

**Pull request merged**
