### PR TITLE
Upgrade deps fix webpack build

### PR DESCRIPTION
**Pull request by Download**
This PR updates all dependencies and makes some changes to the karma configuration to fix the Webpack build breaking due to going from Webpack 1 to Webpack 2. All tests [completed successfully](https://travis-ci.org/Download/preact-helmet) on my branch.

### CODE REVIEW

**Comment by Download** [comment]
It looks like your system is expecting `greenkeeperio-bot` to sign the CLA?

**Comment by cwelch5** [comment]
@Download it says `0 out of 2`, could you try accepting the CLA yourself first to see if that fixes the issue?

**Comment by Download** [comment]
Done.

**Comment by potench** [comment]
Imported `greenkeeper[bot]` into CLA according to this issue greenkeeperio/greenkeeper/issues/236

**Comment by cwelch5** [comment]
@Download Thanks for your contribution.  We did a major refactor with Helmet 5.0.0 that made this PR unnecessary.

**Pull request closed without merging**
