### PR TITLE
Replace deepEqual with react-fast-compare

### LINKED ISSUE #373: Uncaught RangeError: Maximum call stack size exceeded
screenshot 2018-05-03 15 37 05

Hey, 
`HelmetWrapper` uses `deepEqual` to compare props and of course, there are react children components with endless amount of nested objects. 
This seems like a dangerous way to check props equality. Could we turn `HelmetWrapper` into `PureComponent`?

### PR DESCRIPTION
**Pull request by shad-k**
Fixes #373

### CODE REVIEW

**Comment by tmbtech** [comment]
@shad-k looks like there is a failure in the build step. We will need to resolve before merging into master. I will have sometime tomorrow to look deeper into it. In the meantime, is it possible for you to merge master into your PR?

**Comment by shad-k** [comment]
@tmbtech Done.

**Comment by tmbtech** [comment]
@tadjohnston. 

I would like to merge https://github.com/nfl/react-helmet/pull/395 in first. Then we can publish a beta version for feedback. 

Thoughts?

**Comment by rcohen-unext** [comment]
We are running into this issue now on our project as well so the sooner a release can get out the better.

**Comment by ahmedelgabri** [comment]
Agree with others here we also have the same issue, I think releasing this first makes more sense.

**Comment by catamphetamine** [comment]
Is there any ETA on the release of this fix?

**Comment by zubhav** [comment]
There seems to be a lot of projects depending on this fix. Can this be prioritised please?

**Comment by tmbtech** [comment]
Yup. Will address right after the holidays.

**Comment by tadjohnston** [comment]
Thanks @tmbtech! I think the cjs and esm builds are gonna be great, but if it we could get this patched first that would be ideal IMO.

**Pull request merged**
