### PR TITLE
Pull request for inner HTML tag

### PR DESCRIPTION
**Pull request by ErezSha**
You forgot to create a pull request.

### CODE REVIEW

**Comment by cwelch5** [comment]
@romanonthego @nuc @ErezSha - I think we require that all of you sign the CLA in order to merge the PR.  Thanks.

**Comment by nuc** [comment]
Yup, done already!

**Comment by potench** [comment]
@ErezSha the `clahub` failure above links to the wrong page. Here's the CLA, it's missing your signature: https://cla.nfl.com/agreements/nfl/react-helmet

**Comment by ErezSha** [comment]
Sorry for the delay. Just signed it.

**Comment by potench** [comment]
Still missing @romanonthego's digital signature: https://cla.nfl.com/agreements/nfl/react-helmet

**Comment by ttornese** [comment]
really looking forward to this addition :)

**Comment by jks8787** [comment]
this would be a very useful update!

**Comment by potench** [comment]
We still need @romanonthego's CLA signature before we can land this PR. 
Otherwise, consider submitting a new solution + PR if @romanonthego doesn't respond.

**Comment by romanonthego** [comment]
hey again.
it's look good, but hook link give me 404 error.
so what should I do to fix this error?

**Comment by cwelch5** [comment]
@romanonthego sorry but you will have to go here https://cla.nfl.com/agreements/nfl/react-helmet and sign

**Comment by romanonthego** [comment]
still can’t do it, having 500 rails error when click “I agree” :(

**Comment by potench** [comment]
@romanonthego we are looking at the clahub issue, until then so we can accept this, can you email engineers@nfl.com requesting the Individual CLA? I'll email you one you can just reply "accepted" with.

**Comment by potench** [comment]
@romanonthego we are using a new CLA service, you can accept the Individual CLA here https://cla-assistant.io/nfl/react-helmet?pullRequest=101 

All future PRs will get the new cla-assistant.io badge and might require everyone to re-sign.

**Comment by romanonthego** [comment]
now, done

**Comment by ollieayre-oc** [comment]
Hi 

Does anyone know roughly when the version will be updated on npm now that this has been merged?

Thanks

**Comment by cwelch5** [comment]
@ollieayre-oc I'm anticipating within the next couple days if that works.

**Comment by ollieayre-oc** [comment]
@cwelch5 Awesome...thanks for getting back so soon!

**Pull request merged**
